# -*- coding: utf-8 -*-
"""BeautifulSoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KUWMZwOpS5-exuDGnP5vSd6wxTw6p9b
"""

from bs4 import BeautifulSoup
import requests

url = 'https://www.flipkart.com/search?q=laptop&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&sort=relevance'
page = requests.get(url)

page.text

soup = BeautifulSoup(page.text,'html.parser')

soup.title

name = []
price = []
for a in soup.findAll('a',href=True, attrs={'class':'_1fQZEK'}):
    ni = a.find('div', attrs={'class':'_30jeq3 _1_WHN1'})
    pi = a.find('div', attrs={'class':'_4rR01T'})
    name.append(ni.text)
    price.append(pi.text)

import pandas as pd         //#creating data frame 

df = pd.DataFrame(list(zip(name,price)))
df.columns = ['Name','Price']

df